package com.wasmanalyzer.parser;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.ArrayList;
import java.util.List;

/**
 * Pure-Java WebAssembly → WAT (WebAssembly Text Format) converter.
 * No external dependencies — works without wabt installed.
 *
 * Coverage:
 *   - Type section    (func signatures)
 *   - Import section  (func/table/memory/global imports)
 *   - Function section
 *   - Export section
 *   - Memory section
 *   - Global section
 *   - Table section
 *   - Data section    (hex dump + ASCII strings)
 *   - Code section    (opcode-level disassembly)
 *   - Start section
 *   - Element section (table init)
 */
public class WatWriter {

    public String toWat(byte[] wasm) {
        if (wasm == null || wasm.length < 8) return "(error: invalid wasm)";

        ByteBuffer buf = ByteBuffer.wrap(wasm).order(ByteOrder.LITTLE_ENDIAN);
        int magic = buf.getInt();
        if (magic != 0x6D736100) return "(error: bad magic bytes)";
        int version = buf.getInt();

        // First pass: collect type/import/function/export info for name resolution
        WasmModel model = new WasmModel();
        parseModel(wasm, model);

        // Second pass: emit WAT
        StringBuilder sb = new StringBuilder();
        sb.append(";; WebAssembly Text Format — generated by WASM Analyzer (pure Java)\n");
        sb.append(";; Version: ").append(version).append("\n\n");
        sb.append("(module\n");

        buf.position(8);
        while (buf.remaining() >= 2) {
            int sectionId   = buf.get() & 0xFF;
            long sectionLen = readULEB128(buf);
            int  sectionEnd = buf.position() + (int) sectionLen;
            if (sectionEnd > buf.limit()) break;

            switch (sectionId) {
                case 1  -> emitTypeSection(buf, sectionEnd, sb, model);
                case 2  -> emitImportSection(buf, sectionEnd, sb, model);
                case 3  -> skipFunctionSection(buf, sectionEnd);
                case 4  -> emitTableSection(buf, sectionEnd, sb);
                case 5  -> emitMemorySection(buf, sectionEnd, sb);
                case 6  -> emitGlobalSection(buf, sectionEnd, sb, model);
                case 7  -> emitExportSection(buf, sectionEnd, sb, model);
                case 8  -> emitStartSection(buf, sectionEnd, sb, model);
                case 9  -> emitElementSection(buf, sectionEnd, sb, model);
                case 10 -> emitCodeSection(buf, sectionEnd, sb, model);
                case 11 -> emitDataSection(buf, sectionEnd, sb);
                default -> { /* skip unknown/custom */ }
            }

            if (buf.position() < sectionEnd) buf.position(sectionEnd);
        }

        sb.append(")\n");
        return sb.toString();
    }

    // ── Model (first pass) ────────────────────────────────────────────────────

    private static class WasmModel {
        List<String>    funcTypes    = new ArrayList<>(); // "(param i32) (result i32)"
        List<Integer>   funcTypeIdx  = new ArrayList<>(); // function → type index
        List<String>    importedFuncs = new ArrayList<>();
        List<String>    exportNames  = new ArrayList<>();
        int             importFuncCount = 0;
        int             memoryCount  = 0;
        int             tableCount   = 0;

        String funcName(int idx) {
            if (idx < importedFuncs.size()) return "$" + importedFuncs.get(idx);
            return "$f" + idx;
        }
    }

    private void parseModel(byte[] wasm, WasmModel model) {
        ByteBuffer buf = ByteBuffer.wrap(wasm).order(ByteOrder.LITTLE_ENDIAN);
        buf.getInt(); buf.getInt(); // skip magic+version

        while (buf.remaining() >= 2) {
            int sectionId   = buf.get() & 0xFF;
            long sectionLen = readULEB128(buf);
            int  sectionEnd = (int) Math.min(buf.position() + sectionLen, buf.limit());

            try {
                switch (sectionId) {
                    case 1 -> modelTypeSection(buf, sectionEnd, model);
                    case 2 -> modelImportSection(buf, sectionEnd, model);
                    case 3 -> modelFunctionSection(buf, sectionEnd, model);
                    case 7 -> modelExportSection(buf, sectionEnd, model);
                    case 5 -> { model.memoryCount = (int) readULEB128(buf); }
                    case 4 -> { model.tableCount  = (int) readULEB128(buf); }
                }
            } catch (Exception ignored) {}

            if (buf.position() < sectionEnd && sectionEnd <= buf.limit())
                buf.position(sectionEnd);
        }
    }

    private void modelTypeSection(ByteBuffer buf, int end, WasmModel m) {
        int count = (int) readULEB128(buf);
        for (int i = 0; i < count && buf.position() < end; i++) {
            int form = buf.get() & 0xFF;
            if (form != 0x60) continue;
            StringBuilder sig = new StringBuilder();
            int pc = (int) readULEB128(buf);
            for (int p = 0; p < pc && buf.position() < end; p++)
                sig.append("(param ").append(valType(buf.get() & 0xFF)).append(") ");
            int rc = (int) readULEB128(buf);
            for (int r = 0; r < rc && buf.position() < end; r++)
                sig.append("(result ").append(valType(buf.get() & 0xFF)).append(") ");
            m.funcTypes.add(sig.toString().trim());
        }
    }

    private void modelImportSection(ByteBuffer buf, int end, WasmModel m) {
        int count = (int) readULEB128(buf);
        for (int i = 0; i < count && buf.position() < end; i++) {
            String mod  = readStr(buf, end);
            String name = readStr(buf, end);
            int kind    = buf.get() & 0xFF;
            readULEB128(buf);
            if (kind == 0) {
                m.importedFuncs.add(sanitize(mod + "_" + name));
                m.importFuncCount++;
            }
        }
    }

    private void modelFunctionSection(ByteBuffer buf, int end, WasmModel m) {
        int count = (int) readULEB128(buf);
        for (int i = 0; i < count && buf.position() < end; i++)
            m.funcTypeIdx.add((int) readULEB128(buf));
    }

    private void modelExportSection(ByteBuffer buf, int end, WasmModel m) {
        int count = (int) readULEB128(buf);
        for (int i = 0; i < count && buf.position() < end; i++) {
            String name = readStr(buf, end);
            int kind    = buf.get() & 0xFF;
            int idx     = (int) readULEB128(buf);
            if (kind == 0) m.exportNames.add(name);
        }
    }

    // ── Section emitters ──────────────────────────────────────────────────────

    private void emitTypeSection(ByteBuffer buf, int end, StringBuilder sb, WasmModel m) {
        int count = (int) readULEB128(buf);
        for (int i = 0; i < count && buf.position() < end; i++) {
            int form = buf.get() & 0xFF;
            if (form != 0x60) continue;
            sb.append("  (type $t").append(i).append(" (func");
            int pc = (int) readULEB128(buf);
            for (int p = 0; p < pc && buf.position() < end; p++)
                sb.append(" (param ").append(valType(buf.get() & 0xFF)).append(")");
            int rc = (int) readULEB128(buf);
            for (int r = 0; r < rc && buf.position() < end; r++)
                sb.append(" (result ").append(valType(buf.get() & 0xFF)).append(")");
            sb.append("))\n");
        }
    }

    private void emitImportSection(ByteBuffer buf, int end, StringBuilder sb, WasmModel m) {
        int count = (int) readULEB128(buf);
        int fi = 0;
        for (int i = 0; i < count && buf.position() < end; i++) {
            String mod  = readStr(buf, end);
            String name = readStr(buf, end);
            int kind    = buf.get() & 0xFF;
            long idx    = readULEB128(buf);
            switch (kind) {
                case 0 -> sb.append("  (import \"").append(mod).append("\" \"").append(name)
                    .append("\" (func $").append(sanitize(mod + "_" + name))
                    .append(" (type $t").append(idx).append(")))\n");
                case 1 -> sb.append("  (import \"").append(mod).append("\" \"").append(name)
                    .append("\" (table ").append(idx).append(" funcref))\n");
                case 2 -> sb.append("  (import \"").append(mod).append("\" \"").append(name)
                    .append("\" (memory ").append(idx).append("))\n");
                case 3 -> sb.append("  (import \"").append(mod).append("\" \"").append(name)
                    .append("\" (global ").append(idx).append("))\n");
            }
        }
    }

    private void skipFunctionSection(ByteBuffer buf, int end) {
        int count = (int) readULEB128(buf);
        for (int i = 0; i < count && buf.position() < end; i++) readULEB128(buf);
    }

    private void emitTableSection(ByteBuffer buf, int end, StringBuilder sb) {
        int count = (int) readULEB128(buf);
        for (int i = 0; i < count && buf.position() < end; i++) {
            int refType = buf.get() & 0xFF;
            String rt = refType == 0x70 ? "funcref" : "externref";
            int flags = buf.get() & 0xFF;
            long min = readULEB128(buf);
            long max = flags == 1 ? readULEB128(buf) : -1;
            sb.append("  (table $tbl").append(i).append(" ").append(min);
            if (max >= 0) sb.append(" ").append(max);
            sb.append(" ").append(rt).append(")\n");
        }
    }

    private void emitMemorySection(ByteBuffer buf, int end, StringBuilder sb) {
        int count = (int) readULEB128(buf);
        for (int i = 0; i < count && buf.position() < end; i++) {
            int flags = buf.get() & 0xFF;
            long min  = readULEB128(buf);
            long max  = flags == 1 ? readULEB128(buf) : -1;
            sb.append("  (memory $mem").append(i).append(" ").append(min);
            if (max >= 0) sb.append(" ").append(max);
            sb.append(")\n");
        }
    }

    private void emitGlobalSection(ByteBuffer buf, int end, StringBuilder sb, WasmModel m) {
        int count = (int) readULEB128(buf);
        for (int i = 0; i < count && buf.position() < end; i++) {
            int vt  = buf.get() & 0xFF;
            int mut = buf.get() & 0xFF;
            String initExpr = readInitExpr(buf, end, m);
            sb.append("  (global $g").append(i).append(" ")
              .append(mut == 1 ? "(mut " + valType(vt) + ")" : valType(vt))
              .append(" (").append(initExpr).append("))\n");
        }
    }

    private void emitExportSection(ByteBuffer buf, int end, StringBuilder sb, WasmModel m) {
        int count = (int) readULEB128(buf);
        for (int i = 0; i < count && buf.position() < end; i++) {
            String name = readStr(buf, end);
            int kind    = buf.get() & 0xFF;
            int idx     = (int) readULEB128(buf);
            String kindStr = switch (kind) {
                case 0 -> "func";
                case 1 -> "table";
                case 2 -> "memory";
                case 3 -> "global";
                default -> "unknown";
            };
            String ref = switch (kind) {
                case 0 -> m.funcName(idx);
                case 1 -> "$tbl" + idx;
                case 2 -> "$mem" + idx;
                case 3 -> "$g" + idx;
                default -> String.valueOf(idx);
            };
            sb.append("  (export \"").append(name).append("\" (").append(kindStr)
              .append(" ").append(ref).append("))\n");
        }
    }

    private void emitStartSection(ByteBuffer buf, int end, StringBuilder sb, WasmModel m) {
        int idx = (int) readULEB128(buf);
        sb.append("  (start ").append(m.funcName(idx)).append(")\n");
    }

    private void emitElementSection(ByteBuffer buf, int end, StringBuilder sb, WasmModel m) {
        int count = (int) readULEB128(buf);
        for (int i = 0; i < count && buf.position() < end; i++) {
            long flags = readULEB128(buf);
            sb.append("  (elem");
            if (flags == 0) {
                String offset = readInitExpr(buf, end, m);
                sb.append(" (table 0) (offset (").append(offset).append("))");
                int numFuncs = (int) readULEB128(buf);
                sb.append(" func");
                for (int f = 0; f < numFuncs && buf.position() < end; f++)
                    sb.append(" ").append(m.funcName((int) readULEB128(buf)));
            } else {
                // Skip complex element segment forms
                skipToEnd(buf, end);
            }
            sb.append(")\n");
        }
    }

    private void emitDataSection(ByteBuffer buf, int end, StringBuilder sb) {
        int count = (int) readULEB128(buf);
        for (int i = 0; i < count && buf.position() < end; i++) {
            long flags = readULEB128(buf);
            sb.append("  (data");
            if (flags == 0) {
                // active — skip init expr (memory 0, offset)
                skipInitExprRaw(buf, end);
                sb.append(" (memory 0)");
            } else if (flags == 2) {
                int memIdx = (int) readULEB128(buf);
                skipInitExprRaw(buf, end);
                sb.append(" (memory ").append(memIdx).append(")");
            }
            // passive (flags==1): no init expr
            int dataLen = (int) readULEB128(buf);
            int dEnd    = Math.min(buf.position() + dataLen, end);
            byte[] data = new byte[dEnd - buf.position()];
            buf.get(data);
            sb.append(" \"").append(escapeBytes(data)).append("\"");
            sb.append(")\n");
        }
    }

    private void emitCodeSection(ByteBuffer buf, int end, StringBuilder sb, WasmModel m) {
        int count = (int) readULEB128(buf);
        int funcOffset = m.importFuncCount;

        for (int fi = 0; fi < count && buf.position() < end; fi++) {
            int bodySize = (int) readULEB128(buf);
            int bodyEnd  = Math.min(buf.position() + bodySize, end);
            int globalFuncIdx = funcOffset + fi;

            int typeIdx = fi < m.funcTypeIdx.size() ? m.funcTypeIdx.get(fi) : -1;
            String typeSig = typeIdx >= 0 && typeIdx < m.funcTypes.size()
                ? m.funcTypes.get(typeIdx) : "";

            sb.append("  (func ").append(m.funcName(globalFuncIdx));
            if (typeIdx >= 0) sb.append(" (type $t").append(typeIdx).append(")");
            if (!typeSig.isEmpty()) sb.append(" ").append(typeSig);
            sb.append("\n");

            // Locals
            int localGroups = (int) readULEB128(buf);
            for (int lg = 0; lg < localGroups && buf.position() < bodyEnd; lg++) {
                int n  = (int) readULEB128(buf);
                int vt = buf.get() & 0xFF;
                for (int l = 0; l < n; l++)
                    sb.append("    (local ").append(valType(vt)).append(")\n");
            }

            // Opcodes
            disassemble(buf, bodyEnd, sb, m, "    ");
            sb.append("  )\n");

            if (buf.position() < bodyEnd) buf.position(bodyEnd);
        }
    }

    // ── Disassembler ──────────────────────────────────────────────────────────

    private void disassemble(ByteBuffer buf, int end, StringBuilder sb, WasmModel m, String indent) {
        int depth = 0;
        while (buf.position() < end) {
            int op = buf.get() & 0xFF;
            if (op == 0x0B && depth == 0) break; // end of function

            String ind = indent + "  ".repeat(depth);

            switch (op) {
                // Control
                case 0x00 -> sb.append(ind).append("unreachable\n");
                case 0x01 -> sb.append(ind).append("nop\n");
                case 0x02 -> { sb.append(ind).append("(block\n"); depth++; readBlockType(buf); }
                case 0x03 -> { sb.append(ind).append("(loop\n"); depth++; readBlockType(buf); }
                case 0x04 -> { sb.append(ind).append("(if\n"); depth++; readBlockType(buf); }
                case 0x05 -> sb.append(ind).append("else\n");
                case 0x0B -> { depth = Math.max(0, depth-1); sb.append(ind).append(")\n"); }
                case 0x0C -> sb.append(ind).append("br $l").append(readULEB128(buf)).append("\n");
                case 0x0D -> sb.append(ind).append("br_if $l").append(readULEB128(buf)).append("\n");
                case 0x0E -> {
                    int n = (int) readULEB128(buf);
                    sb.append(ind).append("br_table");
                    for (int i = 0; i <= n; i++) sb.append(" $l").append(readULEB128(buf));
                    sb.append("\n");
                }
                case 0x0F -> sb.append(ind).append("return\n");
                case 0x10 -> sb.append(ind).append("call ").append(m.funcName((int) readULEB128(buf))).append("\n");
                case 0x11 -> { long ti = readULEB128(buf); readULEB128(buf); sb.append(ind).append("call_indirect (type $t").append(ti).append(")\n"); }

                // Parametric
                case 0x1A -> sb.append(ind).append("drop\n");
                case 0x1B -> sb.append(ind).append("select\n");

                // Variable
                case 0x20 -> sb.append(ind).append("local.get $l").append(readULEB128(buf)).append("\n");
                case 0x21 -> sb.append(ind).append("local.set $l").append(readULEB128(buf)).append("\n");
                case 0x22 -> sb.append(ind).append("local.tee $l").append(readULEB128(buf)).append("\n");
                case 0x23 -> sb.append(ind).append("global.get $g").append(readULEB128(buf)).append("\n");
                case 0x24 -> sb.append(ind).append("global.set $g").append(readULEB128(buf)).append("\n");

                // Memory load
                case 0x28 -> { long[] ma = memArg(buf); sb.append(ind).append("i32.load offset=").append(ma[1]).append("\n"); }
                case 0x29 -> { long[] ma = memArg(buf); sb.append(ind).append("i64.load offset=").append(ma[1]).append("\n"); }
                case 0x2A -> { long[] ma = memArg(buf); sb.append(ind).append("f32.load offset=").append(ma[1]).append("\n"); }
                case 0x2B -> { long[] ma = memArg(buf); sb.append(ind).append("f64.load offset=").append(ma[1]).append("\n"); }
                case 0x2C -> { long[] ma = memArg(buf); sb.append(ind).append("i32.load8_s offset=").append(ma[1]).append("\n"); }
                case 0x2D -> { long[] ma = memArg(buf); sb.append(ind).append("i32.load8_u offset=").append(ma[1]).append("\n"); }
                case 0x2E -> { long[] ma = memArg(buf); sb.append(ind).append("i32.load16_s offset=").append(ma[1]).append("\n"); }
                case 0x2F -> { long[] ma = memArg(buf); sb.append(ind).append("i32.load16_u offset=").append(ma[1]).append("\n"); }
                case 0x30 -> { long[] ma = memArg(buf); sb.append(ind).append("i64.load8_s offset=").append(ma[1]).append("\n"); }
                case 0x31 -> { long[] ma = memArg(buf); sb.append(ind).append("i64.load8_u offset=").append(ma[1]).append("\n"); }
                case 0x32 -> { long[] ma = memArg(buf); sb.append(ind).append("i64.load16_s offset=").append(ma[1]).append("\n"); }
                case 0x33 -> { long[] ma = memArg(buf); sb.append(ind).append("i64.load16_u offset=").append(ma[1]).append("\n"); }
                case 0x34 -> { long[] ma = memArg(buf); sb.append(ind).append("i64.load32_s offset=").append(ma[1]).append("\n"); }
                case 0x35 -> { long[] ma = memArg(buf); sb.append(ind).append("i64.load32_u offset=").append(ma[1]).append("\n"); }

                // Memory store
                case 0x36 -> { long[] ma = memArg(buf); sb.append(ind).append("i32.store offset=").append(ma[1]).append("\n"); }
                case 0x37 -> { long[] ma = memArg(buf); sb.append(ind).append("i64.store offset=").append(ma[1]).append("\n"); }
                case 0x38 -> { long[] ma = memArg(buf); sb.append(ind).append("f32.store offset=").append(ma[1]).append("\n"); }
                case 0x39 -> { long[] ma = memArg(buf); sb.append(ind).append("f64.store offset=").append(ma[1]).append("\n"); }
                case 0x3A -> { long[] ma = memArg(buf); sb.append(ind).append("i32.store8 offset=").append(ma[1]).append("\n"); }
                case 0x3B -> { long[] ma = memArg(buf); sb.append(ind).append("i32.store16 offset=").append(ma[1]).append("\n"); }
                case 0x3C -> { long[] ma = memArg(buf); sb.append(ind).append("i64.store8 offset=").append(ma[1]).append("\n"); }
                case 0x3D -> { long[] ma = memArg(buf); sb.append(ind).append("i64.store16 offset=").append(ma[1]).append("\n"); }
                case 0x3E -> { long[] ma = memArg(buf); sb.append(ind).append("i64.store32 offset=").append(ma[1]).append("\n"); }

                // Memory misc
                case 0x3F -> { buf.get(); sb.append(ind).append("memory.size\n"); }
                case 0x40 -> { buf.get(); sb.append(ind).append("memory.grow\n"); }

                // Const
                case 0x41 -> sb.append(ind).append("i32.const ").append(readSLEB128_32(buf)).append("\n");
                case 0x42 -> sb.append(ind).append("i64.const ").append(readSLEB128_64(buf)).append("\n");
                case 0x43 -> sb.append(ind).append("f32.const ").append(readF32(buf)).append("\n");
                case 0x44 -> sb.append(ind).append("f64.const ").append(readF64(buf)).append("\n");

                // i32 ops
                case 0x45 -> sb.append(ind).append("i32.eqz\n");
                case 0x46 -> sb.append(ind).append("i32.eq\n");
                case 0x47 -> sb.append(ind).append("i32.ne\n");
                case 0x48 -> sb.append(ind).append("i32.lt_s\n");
                case 0x49 -> sb.append(ind).append("i32.lt_u\n");
                case 0x4A -> sb.append(ind).append("i32.gt_s\n");
                case 0x4B -> sb.append(ind).append("i32.gt_u\n");
                case 0x4C -> sb.append(ind).append("i32.le_s\n");
                case 0x4D -> sb.append(ind).append("i32.le_u\n");
                case 0x4E -> sb.append(ind).append("i32.ge_s\n");
                case 0x4F -> sb.append(ind).append("i32.ge_u\n");
                case 0x50 -> sb.append(ind).append("i64.eqz\n");
                case 0x51 -> sb.append(ind).append("i64.eq\n");
                case 0x52 -> sb.append(ind).append("i64.ne\n");
                case 0x53 -> sb.append(ind).append("i64.lt_s\n");
                case 0x54 -> sb.append(ind).append("i64.lt_u\n");
                case 0x55 -> sb.append(ind).append("i64.gt_s\n");
                case 0x56 -> sb.append(ind).append("i64.gt_u\n");
                case 0x57 -> sb.append(ind).append("i64.le_s\n");
                case 0x58 -> sb.append(ind).append("i64.le_u\n");
                case 0x59 -> sb.append(ind).append("i64.ge_s\n");
                case 0x5A -> sb.append(ind).append("i64.ge_u\n");
                case 0x5B -> sb.append(ind).append("f32.eq\n");
                case 0x5C -> sb.append(ind).append("f32.ne\n");
                case 0x5D -> sb.append(ind).append("f32.lt\n");
                case 0x5E -> sb.append(ind).append("f32.gt\n");
                case 0x5F -> sb.append(ind).append("f32.le\n");
                case 0x60 -> sb.append(ind).append("f32.ge\n");
                case 0x61 -> sb.append(ind).append("f64.eq\n");
                case 0x62 -> sb.append(ind).append("f64.ne\n");
                case 0x63 -> sb.append(ind).append("f64.lt\n");
                case 0x64 -> sb.append(ind).append("f64.gt\n");
                case 0x65 -> sb.append(ind).append("f64.le\n");
                case 0x66 -> sb.append(ind).append("f64.ge\n");
                case 0x67 -> sb.append(ind).append("i32.clz\n");
                case 0x68 -> sb.append(ind).append("i32.ctz\n");
                case 0x69 -> sb.append(ind).append("i32.popcnt\n");
                case 0x6A -> sb.append(ind).append("i32.add\n");
                case 0x6B -> sb.append(ind).append("i32.sub\n");
                case 0x6C -> sb.append(ind).append("i32.mul\n");
                case 0x6D -> sb.append(ind).append("i32.div_s\n");
                case 0x6E -> sb.append(ind).append("i32.div_u\n");
                case 0x6F -> sb.append(ind).append("i32.rem_s\n");
                case 0x70 -> sb.append(ind).append("i32.rem_u\n");
                case 0x71 -> sb.append(ind).append("i32.and\n");
                case 0x72 -> sb.append(ind).append("i32.or\n");
                case 0x73 -> sb.append(ind).append("i32.xor\n");
                case 0x74 -> sb.append(ind).append("i32.shl\n");
                case 0x75 -> sb.append(ind).append("i32.shr_s\n");
                case 0x76 -> sb.append(ind).append("i32.shr_u\n");
                case 0x77 -> sb.append(ind).append("i32.rotl\n");
                case 0x78 -> sb.append(ind).append("i32.rotr\n");
                case 0x79 -> sb.append(ind).append("i64.clz\n");
                case 0x7A -> sb.append(ind).append("i64.ctz\n");
                case 0x7B -> sb.append(ind).append("i64.popcnt\n");
                case 0x7C -> sb.append(ind).append("i64.add\n");
                case 0x7D -> sb.append(ind).append("i64.sub\n");
                case 0x7E -> sb.append(ind).append("i64.mul\n");
                case 0x7F -> sb.append(ind).append("i64.div_s\n");
                case 0x80 -> sb.append(ind).append("i64.div_u\n");
                case 0x81 -> sb.append(ind).append("i64.rem_s\n");
                case 0x82 -> sb.append(ind).append("i64.rem_u\n");
                case 0x83 -> sb.append(ind).append("i64.and\n");
                case 0x84 -> sb.append(ind).append("i64.or\n");
                case 0x85 -> sb.append(ind).append("i64.xor\n");
                case 0x86 -> sb.append(ind).append("i64.shl\n");
                case 0x87 -> sb.append(ind).append("i64.shr_s\n");
                case 0x88 -> sb.append(ind).append("i64.shr_u\n");
                case 0x89 -> sb.append(ind).append("i64.rotl\n");
                case 0x8A -> sb.append(ind).append("i64.rotr\n");
                case 0x8B -> sb.append(ind).append("f32.abs\n");
                case 0x8C -> sb.append(ind).append("f32.neg\n");
                case 0x8D -> sb.append(ind).append("f32.ceil\n");
                case 0x8E -> sb.append(ind).append("f32.floor\n");
                case 0x8F -> sb.append(ind).append("f32.trunc\n");
                case 0x90 -> sb.append(ind).append("f32.nearest\n");
                case 0x91 -> sb.append(ind).append("f32.sqrt\n");
                case 0x92 -> sb.append(ind).append("f32.add\n");
                case 0x93 -> sb.append(ind).append("f32.sub\n");
                case 0x94 -> sb.append(ind).append("f32.mul\n");
                case 0x95 -> sb.append(ind).append("f32.div\n");
                case 0x96 -> sb.append(ind).append("f32.min\n");
                case 0x97 -> sb.append(ind).append("f32.max\n");
                case 0x98 -> sb.append(ind).append("f32.copysign\n");
                case 0x99 -> sb.append(ind).append("f64.abs\n");
                case 0x9A -> sb.append(ind).append("f64.neg\n");
                case 0x9B -> sb.append(ind).append("f64.ceil\n");
                case 0x9C -> sb.append(ind).append("f64.floor\n");
                case 0x9D -> sb.append(ind).append("f64.trunc\n");
                case 0x9E -> sb.append(ind).append("f64.nearest\n");
                case 0x9F -> sb.append(ind).append("f64.sqrt\n");
                case 0xA0 -> sb.append(ind).append("f64.add\n");
                case 0xA1 -> sb.append(ind).append("f64.sub\n");
                case 0xA2 -> sb.append(ind).append("f64.mul\n");
                case 0xA3 -> sb.append(ind).append("f64.div\n");
                case 0xA4 -> sb.append(ind).append("f64.min\n");
                case 0xA5 -> sb.append(ind).append("f64.max\n");
                case 0xA6 -> sb.append(ind).append("f64.copysign\n");
                case 0xA7 -> sb.append(ind).append("i32.wrap_i64\n");
                case 0xA8 -> sb.append(ind).append("i32.trunc_f32_s\n");
                case 0xA9 -> sb.append(ind).append("i32.trunc_f32_u\n");
                case 0xAA -> sb.append(ind).append("i32.trunc_f64_s\n");
                case 0xAB -> sb.append(ind).append("i32.trunc_f64_u\n");
                case 0xAC -> sb.append(ind).append("i64.extend_i32_s\n");
                case 0xAD -> sb.append(ind).append("i64.extend_i32_u\n");
                case 0xAE -> sb.append(ind).append("i64.trunc_f32_s\n");
                case 0xAF -> sb.append(ind).append("i64.trunc_f32_u\n");
                case 0xB0 -> sb.append(ind).append("i64.trunc_f64_s\n");
                case 0xB1 -> sb.append(ind).append("i64.trunc_f64_u\n");
                case 0xB2 -> sb.append(ind).append("f32.convert_i32_s\n");
                case 0xB3 -> sb.append(ind).append("f32.convert_i32_u\n");
                case 0xB4 -> sb.append(ind).append("f32.convert_i64_s\n");
                case 0xB5 -> sb.append(ind).append("f32.convert_i64_u\n");
                case 0xB6 -> sb.append(ind).append("f32.demote_f64\n");
                case 0xB7 -> sb.append(ind).append("f64.convert_i32_s\n");
                case 0xB8 -> sb.append(ind).append("f64.convert_i32_u\n");
                case 0xB9 -> sb.append(ind).append("f64.convert_i64_s\n");
                case 0xBA -> sb.append(ind).append("f64.convert_i64_u\n");
                case 0xBB -> sb.append(ind).append("f64.promote_f32\n");
                case 0xBC -> sb.append(ind).append("i32.reinterpret_f32\n");
                case 0xBD -> sb.append(ind).append("i64.reinterpret_f64\n");
                case 0xBE -> sb.append(ind).append("f32.reinterpret_i32\n");
                case 0xBF -> sb.append(ind).append("f64.reinterpret_i64\n");
                case 0xC0 -> sb.append(ind).append("i32.extend8_s\n");
                case 0xC1 -> sb.append(ind).append("i32.extend16_s\n");
                case 0xC2 -> sb.append(ind).append("i64.extend8_s\n");
                case 0xC3 -> sb.append(ind).append("i64.extend16_s\n");
                case 0xC4 -> sb.append(ind).append("i64.extend32_s\n");

                // SIMD / misc prefix
                case 0xFC -> { readULEB128(buf); sb.append(ind).append(";; misc op\n"); }
                case 0xFD -> { readULEB128(buf); sb.append(ind).append(";; simd op\n"); }

                default -> sb.append(ind).append(String.format(";; 0x%02X (unknown)\n", op));
            }
        }
    }

    // ── Low-level helpers ─────────────────────────────────────────────────────

    private String valType(int b) {
        return switch (b) {
            case 0x7F -> "i32";
            case 0x7E -> "i64";
            case 0x7D -> "f32";
            case 0x7C -> "f64";
            case 0x7B -> "v128";
            case 0x70 -> "funcref";
            case 0x6F -> "externref";
            default   -> "i32"; // fallback
        };
    }

    private void readBlockType(ByteBuffer buf) {
        int b = buf.get() & 0xFF;
        if (b == 0x40) return; // empty
        if (b >= 0x70) return; // value type
        // type index (multi-value) — SLEB128
        if ((b & 0x80) != 0) readULEB128(buf);
    }

    private String readInitExpr(ByteBuffer buf, int end, WasmModel m) {
        if (!buf.hasRemaining() || buf.position() >= end) return "i32.const 0";
        int op = buf.get() & 0xFF;
        return switch (op) {
            case 0x41 -> "i32.const " + readSLEB128_32(buf);
            case 0x42 -> "i64.const " + readSLEB128_64(buf);
            case 0x43 -> "f32.const " + readF32(buf);
            case 0x44 -> "f64.const " + readF64(buf);
            case 0x23 -> "global.get $g" + readULEB128(buf);
            default   -> "i32.const 0";
        };
    }

    private void skipInitExprRaw(ByteBuffer buf, int end) {
        while (buf.position() < end && buf.hasRemaining()) {
            if ((buf.get() & 0xFF) == 0x0B) break;
        }
    }

    private long[] memArg(ByteBuffer buf) {
        return new long[]{ readULEB128(buf), readULEB128(buf) };
    }

    private void skipToEnd(ByteBuffer buf, int end) {
        buf.position(end);
    }

    private String escapeBytes(byte[] data) {
        StringBuilder sb = new StringBuilder();
        for (byte b : data) {
            int v = b & 0xFF;
            if (v >= 0x20 && v < 0x7F && v != '"' && v != '\\') {
                sb.append((char) v);
            } else {
                sb.append(String.format("\\%02x", v));
            }
        }
        return sb.toString();
    }

    private String sanitize(String s) {
        return s.replaceAll("[^a-zA-Z0-9_]", "_");
    }

    private String readStr(ByteBuffer buf, int end) {
        int len = (int) readULEB128(buf);
        if (len <= 0 || buf.position() + len > end || buf.position() + len > buf.limit()) return "";
        byte[] b = new byte[len];
        buf.get(b);
        return new String(b, java.nio.charset.StandardCharsets.UTF_8);
    }

    private long readULEB128(ByteBuffer buf) {
        long r = 0; int s = 0;
        while (buf.hasRemaining() && s < 63) {
            int b = buf.get() & 0xFF;
            r |= (long)(b & 0x7F) << s;
            if ((b & 0x80) == 0) break;
            s += 7;
        }
        return r;
    }

    private int readSLEB128_32(ByteBuffer buf) {
        int r = 0, s = 0;
        while (buf.hasRemaining()) {
            int b = buf.get() & 0xFF;
            r |= (b & 0x7F) << s;
            s += 7;
            if ((b & 0x80) == 0) {
                if (s < 32 && (b & 0x40) != 0) r |= -(1 << s);
                break;
            }
        }
        return r;
    }

    private long readSLEB128_64(ByteBuffer buf) {
        long r = 0; int s = 0;
        while (buf.hasRemaining()) {
            int b = buf.get() & 0xFF;
            r |= (long)(b & 0x7F) << s;
            s += 7;
            if ((b & 0x80) == 0) {
                if (s < 64 && (b & 0x40) != 0) r |= -(1L << s);
                break;
            }
        }
        return r;
    }

    private float readF32(ByteBuffer buf) {
        return buf.getFloat();
    }

    private double readF64(ByteBuffer buf) {
        return buf.getDouble();
    }
}
